[package]
name = "rust"
version = "0.1.0"
authors = ["the_sociophobic <torikowashi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.8"
listenfd = "0.3"
rusted_cypher = "1.1.0"
