const whiteList = [
  'the_sociophobic',
  'IhuliR',
  'fedlud',
  'Etozheanton',
  'teeema',
  'Grendaiser',
  'krsbr',
  'ohhw0w',
  'Teodor_Rusveld',
  'mereanamordegaard',
  'youngatom',
  'tabronnikova',
  'GUREN17890987',
  'artaksarta',
  'sisterslo',
  'zamechatelno',
  'katia_1520',
  'NickDanilch',
  'pokemon_cinnamonsantonica',
  'username00707',
  'gglchrm',
  'smeiznai',
  'baklazhe',
  'operakino',
  'yslpn',
  'kotvvedre',
  'danek',
  'HouseOnSpurs',
  'kirakastaneda',
  'kseny_wall',
]


export default whiteList